version: '3.9'
services:
  mysql:
    container_name: 'mysql-demo'
    image: 'mysql:5.7'
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'testDB'
    volumes:
        - mysql-data:/var/lib/mysql
    networks:
        - 'two-tier'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      retries: 5
      start_period: 30s




  flask-app:
    build:
      context: .
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: 'mysql-demo'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_DB: 'testDB'
    networks:
      - 'two-tier'
    depends_on:
      mysql:
        condition: service_healthy


volumes:
  mysql-data:
networks:
  two-tier:
    driver: 'bridge'
